### ISSUE TITLE
update some vehicle spawn shortcuts

### ISSUE THREAD

**Issue by manchesterjm** [hexarobi/stand-lua-hexascript#1]
d10 = "coquette4",
    xxr = "entity2",
    bug = "weevil",
    rsx = "italirsx",
    stx = "buffalo4",
    gtx = "dominator3",
    asp = "dominator7",
    gtt = "dominator8",
    dod = "dukes2",
    tank2 = "khanjali",
    tm02 = "khanjali",
    tank3 = "minitank",
    reaver = "reever",
    cabrio = "cogcabrio",
    ["370z"] = "euros",
    drag = "hakuchou2",
    ramp2 = "dune5",
    mini = "issi2",
    tb = "terbyte",
    lf22 = "starling",
    fh1 = "hunter",

**Comment by hexarobi** [comment]
nice! thanks for this =)
