### ISSUE TITLE
added more aliases

### ISSUE THREAD

**Issue by manchesterjm** [hexarobi/stand-lua-hexascript#2]
gtb = "italigtb",
    gtb2 = "italigtb2",
    xo = "torero2",
    dv8 = "deveste",
    roosevelt = "btype",
    frankenstange = "btype2",
    stange = "btype2",
    valor = "btype3",
    vette = "coquette2",
    stirling = "feltzer3",
    bond = "jb700",
    bond2 = "jb7002",
    bennyspeyote = "peyote3",
    bennystornado = "tornado5",
    gogo = "blista3",
    bennyscomet = "comet3",
    bennysspecter = "specter2",
    bennysbanshee = "banshee2",
    bennysmanana = "manana2",
    bennysgtb = "italigtb2",
    bennysnero = "nero2",
    bennysdonk = "faction3",
    donk = "faction3",
    bennysminivan = "minivan2",
    bennyssabre = "sabregt2",
    bennysvirgo = "virgo2",
    bennysbuccaneer = "buccaneer2",
    bennyschino = "chino2",
    bennysfaction = "faction2",
    bennysvoodoo = "voodoo",
    bennysgauntlet = "gauntlet5",

**Comment by hexarobi** [comment]
added thx! =)
